CREATE TABLE CLIENTE (
    ID integer primary key AUTO_INCREMENT,
    NOME VARCHAR(100),
    CPF VARCHAR(14)
);

CREATE TABLE PRODUTO (
     ID integer primary key AUTO_INCREMENT,
     DESCRICAO VARCHAR(100),
     PRECO_UNITARIO NUMERIC(20,2)
 );

CREATE TABLE PEDIDO (
     ID integer primary key AUTO_INCREMENT,
     CLIENTE_ID INTEGER REFERENCES CLIENTE(ID),
     DATA_PEDIDO TIMESTAMP,
     TOTAL NUMERIC(20,2)
 );

CREATE TABLE ITEM_PEDIDO (
     ID integer primary key AUTO_INCREMENT,
     PEDIDO_ID INTEGER REFERENCES PEDIDO(ID),
     PRODUTO_ID INTEGER REFERENCES PRODUTO(ID),
     QUANTIDADE INTEGER DEFAULT 1
 );

CREATE TABLE USUARIO(
	id INTEGER PRIMARY KEY AUTO_INCREMENT
    , LOGIN VARCHAR(50) NOT NULL
    , SENHA VARCHAR(255) NOT NULL
    , ADMIN BOOL DEFAULT FALSE
)
